### ISSUE TITLE
Remove path title tooltip on select

### ISSUE THREAD

**Issue by saltyskip** [hovanter/footsteps#33]
The info is already on the card, no need to display it on the map as well. Notsure where the popup call is coming from

**Comment by bhnascar** [comment]
What if we just changed the tooltip text? Unfortunately we need a popup of some sort because the card trigger hooks into popup trigger. There's no other appropriate event we can listen to - click() is a candidate but there's no matching "unclick" event for when the user clicks somewhere on the map to dismiss the card (apparently "blur" events, i.e. losing focus, are not implemented by MapBox). The popup event fires a matching "popupopen" and "popupclose" pair.

**Comment by bhnascar** [comment]
Deferring this issue to after we have decided on doing Tokyo stuff or not.

**Comment by bhnascar** [comment]
Done with the new Tokyo stuff.
